FROM ubuntu:20.04 as onStrat

# ubuntu LTS 20.04 和 pip 的清华镜像
ARG tunaOS="https://mirrors.tuna.tsinghua.edu.cn/ubuntu/"
ARG tunaPIP="https://pypi.tuna.tsinghua.edu.cn/simple"

# alpine 和 pip 使用清华镜像
RUN sed -i 's|http://security.ubuntu.com/ubuntu/|'${tunaOS}'|g' /etc/apt/sources.list \
    && python -m pip config set global.index-url ${tunaPIP}

# 更新 pip 安装依赖
RUN pip install pip pyinstaller aiohttp -U

# build

# COPY ./src/大脚插件自动更新_异步.py /work

RUN ls -al /work


# RUN pyinstaller -F -w ./src/大脚插件自动更新_异步.py -i wow.ico
